Homework8task1
Volodya-Petrov/Homework pull request #14
Opened 2020-11-17 17:45 UTC by Volodya-Petrov

2020-12-07 11:47 UTC, yurii-litvinov requested changes
В целом всё очень неплохо, но надо ещё тесты.

2020-12-07 11:47 UTC, yurii-litvinov commented on Homework8 - task1/Homework8 - task1/Homework8 - task1.c
> +			int key = correctInput();
По условию и ключи, и значения должны быть char *. Чтобы страдать от слежения за памятью и сравнения строк вдвое больше.

2020-12-07 11:47 UTC, yurii-litvinov commented on Homework8 - task1/Homework8 - task1/Homework8 - task1.c
> +			char value[20] = "\0";
Вместо "\0" правильнее ""

2020-12-07 11:47 UTC, yurii-litvinov commented on Homework8 - task1/Homework8 - task1/Homework8 - task1.c
> +			printf("Введите значение ключа: ");
Значение же не ключа, а просто значение

2020-12-07 11:47 UTC, yurii-litvinov commented on Homework8 - task1/Homework8 - task1/Homework8 - task1.c
> +			printf("Значение по заданному ключе: %s\n", value);
"по заданному ключ**у**"

2020-12-07 11:47 UTC, yurii-litvinov commented on Homework8 - task1/Homework8 - task1/avl.c
> +}Node;
Надо пробел после "}"

2020-12-07 11:47 UTC, yurii-litvinov commented on Homework8 - task1/Homework8 - task1/avl.h
> +void insert(Tree* tree, int key, char* value);
Вообще, в C и C++ принято про каждый указатель писать в комментарии, принимает ли структура данных владение указателем или оставляет его вызывающему. Владение --- это кто должен его удалить. Про tree писать не надо, потому что это и есть та самая структура данных, ей владеет, очевидно, вызывающий. А вот про value я бы тут написал, что insert делает копию value, оставляя владение исходным value вызывающему. Такие комментарии позволяют избежать утечек памяти, не читая реализацию функций.

2020-12-07 11:47 UTC, yurii-litvinov commented on Homework8 - task1/Homework8 - task1/avl.c
> +	return newTree;
Можно было сразу `return calloc(1, sizeof(Tree));` (разве что для отладки такая запись, как у Вас, полезна).

2020-12-07 11:47 UTC, yurii-litvinov commented on Homework8 - task1/Homework8 - task1/avl.c
> +	node->height = (hright > hleft ? hright : hleft) + 1;
Копипаст из интернетов? Копипаст ок, но после некоторой чистки --- у нас за имена типа hleft и hright задача не зачитывается сразу :)

2020-12-07 11:47 UTC, yurii-litvinov commented on Homework8 - task1/Homework8 - task1/avl.c
> +void overHeight(Node* node)
Ну и это плохое имя функции. updateHeight лучше

2020-12-07 11:47 UTC, yurii-litvinov commented on Homework8 - task1/Homework8 - task1/avl.h
> +// �������� ������������� �����
"проверка существовани**я** ключа"

2020-12-07 11:47 UTC, yurii-litvinov commented on Homework8 - task1/Homework8 - task1/avl.h
> +// ��������� �������� �� �����
"получение значени**я** по ключу" :)

2020-12-07 11:47 UTC, yurii-litvinov commented on Homework8 - task1/Homework8 - task1/avl.c
> +	return true;
Ужасно :) Это в одну строчку надо писать

2020-12-07 11:47 UTC, yurii-litvinov commented on Homework8 - task1/Homework8 - task1/avl.c
> +	}
Это можно в одну строчку записать тернарным оператором: `return node->left ? searchMin(node->left) : node;`

2020-12-07 11:47 UTC, yurii-litvinov commented on Homework8 - task1/Homework8 - task1/avl.c
> +	if (node->left == NULL)
А выше было `if (node->left)`. Мне вариант с == NULL больше нравится, потому что не требует неявного преобразования типов от указателя к bool и, например, в C# штуки типа `if (node->left)` не скомпилятся (он менее либерален в плане преобразований).

2020-12-07 11:47 UTC, yurii-litvinov commented on Homework8 - task1/Homework8 - task1/avl.c
> +	if (tree == NULL)
Если тут tree проверяется на NULL (что хорошо и правильно), то и во всех остальных функциях должно.

2020-12-07 15:49 UTC, Volodya-Petrov commented on Homework8 - task1/Homework8 - task1/avl.c
> +	node->height = (hright > hleft ? hright : hleft) + 1;
извините, я из нижнего интернета

2020-12-07 15:51 UTC, Volodya-Petrov commented on Homework8 - task1/Homework8 - task1/avl.h
> +// �������� ������������� �����
94 балла по рузгому

2020-12-24 18:57 UTC, yurii-litvinov requested changes
Компилятор весьма не одобряет происходящее (там где-то key передаётся как int до сих пор), всё остальное очень круто. Поправите предупреждения --- будет зачтена.

2020-12-27 16:22 UTC, yurii-litvinov approved these changes
👍

2020-12-27 19:33 UTC, merged