Homework4task3
Volodya-Petrov/Homework pull request #2
Opened 2020-10-10 16:02 UTC by Volodya-Petrov

Первая версия программы для проверки

2020-10-11 08:32 UTC, yurii-litvinov requested changes
Пока 1.5 из 3

2020-10-11 08:32 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +#include "terehovjokes.h"
Файлы лучше тоже в camelCase именовать

2020-10-11 08:32 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +struct person // структура котакта, которая имеет два поля: номер и имя
Структуры, как и все типы, по нашему стайлгайду именуются с заглавной

2020-10-11 08:32 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +struct person // структура котакта, которая имеет два поля: номер и имя
А комментарии пишутся над комментируемой сущностью. "котакта", кстати, опечатка :)

2020-10-11 08:32 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +		if (strcmp(&array1[i].name, &array2[i].name) != 0)
Тут амперсанды не нужны, массивы и так указатели. `&array1[i].name[0]` было бы правильно, но это то же самое, что array1[i].name. Компилятор ругается, кстати.

2020-10-11 08:32 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +	return 0;
Это по смыслу явно булевая функция, стоило бы использовать bool/true/false из stdbool

2020-10-11 08:32 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +void readFromFile(char fileName[] , struct person array[], int *indexOfArray) // функция для считывания данных с файла в массив структур
fileName вряд ли планируется менять, стоит его передавать как const char *

2020-10-11 08:32 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +int numberSearching(int* indexInPresent, struct person phoneBook[], char* name) // поиск телефонного номера по имени в массиве структур
indexInPresent точно надо передавать по указателю? Кажется, он не меняется и не должен меняться нигде внутри

2020-10-11 08:32 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +		if (strcmp(&phoneBook[i].name, name) == 0)
Тоже амперсанд лишний

2020-10-11 08:32 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +void contactAddition(int* indexInPresent, struct person phoneBook[]) // добавление в массив стурктур нового контакта
"стурктур", опечатка

2020-10-11 08:32 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +	if (nameSearching(indexInPresent, phoneBook, phoneBook[*indexInPresent].number) != -1337)
Лучше -1337 задефайнить где-нибудь в начале, чтобы не использовать в коде магических чисел

2020-10-11 08:32 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +	struct person persons[] = { 123, "Jon", 5555, "Teddy", 666, "Joker" };
Это было бы более читаемо в виде `{ { 123, "Jon" }, { 5555, "Teddy" }, { 666, "Joker" } };`

2020-10-11 08:32 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +	return 0;
Тесты все тоже стоило бы сделать булевыми

2020-10-11 08:32 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +			if (numberSearching(&indexOfPhoneBook, phoneBook, &name) == -1337)
И тут лишний амперсанд у name

2020-10-11 08:32 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/terehovjokes.c
> +	printf("�������. ���� ������� ����������\n������� �������\n-�������?\n-20\n-���� 20?\n-� ���� �������?\n");
Терехов рассказывает это в варианте "Два человека кричат друг другу с разных берегов реки". Про коньяк ни разу не слышал :)

2020-10-11 08:32 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/terehovjokes.c
> +#include <stdio.h>
Надо свой .h-ник всегда подключать, желательно первой же строчкой

2020-10-11 08:44 UTC, yurii-litvinov commented
О, кстати, ещё конфликт с мастером, который надо разрешить (просто смерджить (проще даже спуллить) мастер в эту ветку)

2020-10-11 14:38 UTC, Volodya-Petrov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +#include "terehovjokes.h"
исправлено

2020-10-11 14:38 UTC, Volodya-Petrov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +struct person // структура котакта, которая имеет два поля: номер и имя
исправлено

2020-10-11 14:39 UTC, Volodya-Petrov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +struct person // структура котакта, которая имеет два поля: номер и имя
исправлено

2020-10-11 14:39 UTC, Volodya-Petrov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +		if (strcmp(&array1[i].name, &array2[i].name) != 0)
исправлено

2020-10-11 14:39 UTC, Volodya-Petrov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +	return 0;
исправлено

2020-10-11 14:39 UTC, Volodya-Petrov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +	struct person persons[] = { 123, "Jon", 5555, "Teddy", 666, "Joker" };
исправлено

2020-10-11 14:39 UTC, Volodya-Petrov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +			if (numberSearching(&indexOfPhoneBook, phoneBook, &name) == -1337)
исправлено

2020-10-11 14:39 UTC, Volodya-Petrov commented on Homework4-task3/Homework4-task3/terehovjokes.c
> +	printf("�������. ���� ������� ����������\n������� �������\n-�������?\n-20\n-���� 20?\n-� ���� �������?\n");
Да, он нам именно в этом виде рассказывал, но я к сожалению дословно не запомнил. Хорошо, что вы вспомнили. У предыдущих годов про коньяк эта шутка была, мне кажется, что так смешнее)

2020-10-11 14:39 UTC, Volodya-Petrov commented on Homework4-task3/Homework4-task3/terehovjokes.c
> +#include <stdio.h>
исправлено

2020-10-12 17:03 UTC, yurii-litvinov requested changes

2020-10-12 17:03 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/terehovjokes.h
> +#pragma once
Оо, а старые файлы не удалили, теперь получение этого репозитория под виндой может быть довольно хаотичным. А что бы это исправить, нужна регистрозависимая файловая система. Хороший повод поставить себе Ubuntu :) Хотя ладно, можно просто через интерфейс GitHub-а удалить.

2020-10-12 17:03 UTC, yurii-litvinov commented on Test 2/Test 2/Test 2.vcxproj
> +<<<<<<< HEAD
Фэйл :) Зачем эти файлы вообще было коммитить?

2020-10-12 17:03 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/terehovJokes.h
> +void jokesAndIntrestingStories(int number); // ������� �������� � ���������
Комментарии пишутся над комментируемой сущностью.

2020-10-12 17:03 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +// структура контакта, которая имеет два поля: номер и имя
Неправда

2020-10-12 17:03 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +void readFromFile(const char fileName[] , struct Person array[], int *indexOfArray)
Пробел перед "," лишний

2020-10-12 17:03 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +	if (*indexInPresent >= 99)
99 --- тоже магическое число, и его тоже стоило бы задефайнить

2020-10-12 17:03 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +	checkForMistakes = !testWriteInFile() + !testReadFromFile() + !testNumberSearch() + !testNameSearch();
Не-а. "А давайте положим в checkForMistakes ноль. Ой, нет, я передумал, давайте лучше вот эту штуку". Да эту переменную и вообще можно не объявлять, return-ите сразу сумму результатов тестов

2020-10-16 12:21 UTC, yurii-litvinov approved these changes
Эта задача зачтена. Вы её радостно смерджите с мастером, удалите весь код с контрольной и научитесь смотреть диффы (и может даже откатывать мердж-коммиты) :)

2020-10-16 12:21 UTC, yurii-litvinov commented on Homework4-task3/Homework4-task3/Homework4-task3.c
> +void contactAddition(int* indexInPresent, struct Person phoneBook[])
Лучше addContact

2020-10-16 12:21 UTC, yurii-litvinov commented on Test 2/Test 2.sln
> -﻿
А за что Вы в этом пуллреквесте хотите уничтожить задачи с контрольной?

2020-10-19 14:41 UTC, merged