Homework5task2
Volodya-Petrov/Homework pull request #5
Opened 2020-10-25 17:36 UTC by Volodya-Petrov

задача 2 на проверку

2020-10-26 17:09 UTC, yurii-litvinov requested changes
Зачем же пуллреквест не в мастер, а в Stack? :) В диффе сам стек не показывается, понятное дело. А должен. Там, кстати, результат malloc не проверяется, так что если по тем или иным причинам malloc вернёт NULL, всё упадёт. И из pop по-хорошему нельзя возвращать 0 в случае ошибки, потому что 0 может быть вполне валидным значением, и вызывающий даже не узнает, что всё плохо.

2020-10-26 17:09 UTC, yurii-litvinov commented on Homework5 - task2/Homework5 - task2/dynamicStringReader.c
> +		string[(*length)++] = charInReal;
Одна строка --- одно действие. В Си некоторые любят такую жесть, но лучше писать так:
```c
string[*length] = charInReal;
(*length)++;
```
Иначе инкремент легко не заметить посреди другого выражения и неправильно понять программу.

2020-10-26 17:09 UTC, yurii-litvinov commented on Homework5 - task2/Homework5 - task2/dynamicStringReader.c
> +	while ( charInReal != '\n')
Лишний пробел

2020-10-26 17:09 UTC, yurii-litvinov commented on Homework5 - task2/Homework5 - task2/dynamicStringReader.c
> +			string = (char*)realloc(string, capacity * sizeof(char));
По-хорошему, надо проверять, что realloc успешен, и только в этом случае присваивать string. Иначе он вернёт NULL и затрёт указатель на предыдущий string, что вызовет утечку памяти. Мне кажется, Visual Studio подсказывает это

2020-10-26 17:09 UTC, yurii-litvinov commented on Homework5 - task2/Homework5 - task2/isBalanced.c
> +			push(bracketStack, 1);
Лучше уж enum завести, чтобы не думать, что из них 1, 2 или 3. Или хранить прямо символы, `push(bracketStack, (int)'(');` тоже прекрасно сработает. И позволит сэкономить много копипаста, потому что все открывающиеся скобики так можно единообразно обработать. А если ещё сделать функцию-предикат, проверяющую две скобки на парность, то и с закрывающими скобками разобраться без дублирования кода

2020-10-26 17:09 UTC, yurii-litvinov commented on Homework5 - task2/Homework5 - task2/isBalanced.c
> +				return false;
И стек никто не удалит, мемлик

2020-10-26 17:09 UTC, yurii-litvinov commented on Homework5 - task2/Homework5 - task2/Homework5 - task2.c
> +	free(string);
Предупреждение компилятора

2020-10-30 19:28 UTC, Volodya-Petrov commented
оставлю этот пуллреквест, чтобы можно было посмотреть, где раньше были ошибки

2020-11-09 21:11 UTC, closed without merging